### ISSUE TITLE
不能安装MOD

### ISSUE THREAD

**Issue by gongminan** [Small-Miao/ModBoxIssues#3]
今天把所有2.0单机版盒子的mod都删了。换了联网版本，但是mod安装不上。
而且显示未安装前置，软件安装前置之后也是不能安装mod，卸载前置；安装前置，甚至手动安装前置都来回试好多次了，还是不能安装mod，确切的说不是所有的mod都能安装，比如A大的外观mod就可以装，好像除了A大的其他的mod大部分都装不了。
后面换回单机版试了可以装。

**Comment by Small-Miao** [comment]
关于这个问题 并不是mod没有安装上 而是并没有扫描mod mod扫描是通过扫描指定的目录来进行管理。这个将在后面版本进行更改结构来进行支持不扫描目录mod的管理

**Comment by Small-Miao** [comment]
关闭
