### ISSUE TITLE
无法更新前置

### ISSUE THREAD

**Issue by Abel2333** [Small-Miao/ModBoxIssues#6]
显示端口被占用，应该如何更改狩技使用的端口？
或者显示被占用的端口
也没个日志啥的

**Comment by Small-Miao** [comment]
端口与前置无关，端口可能为爱奇艺占用，端口主为网页一键安装

**Comment by Abel2333** [comment]
但是我没有安装爱奇艺，而且现象是无法安装前置

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Small-Miao<mailto:notifications@github.com>
发送时间: 2020年10月29日 14:02
收件人: Small-Miao/ModBoxIssues<mailto:ModBoxIssues@noreply.github.com>
抄送: Abel<mailto:abelsparda@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [Small-Miao/ModBoxIssues] 无法更新前置 (#6)


端口与前置无关，端口可能为爱奇艺占用，端口主为网页一键安装

―
